# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/elias/Projects/PearlEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/elias/Projects/PearlEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"dev\" \"doc\" \"examples\" \"pkgconfig\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/elias/Projects/PearlEngine/CMakeFiles /home/elias/Projects/PearlEngine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/elias/Projects/PearlEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/elias/Projects/PearlEngine/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named game_engine

# Build rule for target.
game_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game_engine
.PHONY : game_engine

# fast build rule for target.
game_engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/build
.PHONY : game_engine/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f external/glfw/CMakeFiles/uninstall.dir/build.make external/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f external/glfw/src/CMakeFiles/glfw.dir/build.make external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f external/glfw/src/CMakeFiles/update_mappings.dir/build.make external/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named travis_doc

# Build rule for target.
travis_doc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 travis_doc
.PHONY : travis_doc

# fast build rule for target.
travis_doc/fast:
	$(MAKE) $(MAKESILENT) -f external/rapidjson/CMakeFiles/travis_doc.dir/build.make external/rapidjson/CMakeFiles/travis_doc.dir/build
.PHONY : travis_doc/fast

external/glad/src/glad.o: external/glad/src/glad.c.o
.PHONY : external/glad/src/glad.o

# target to build an object file
external/glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/external/glad/src/glad.c.o
.PHONY : external/glad/src/glad.c.o

external/glad/src/glad.i: external/glad/src/glad.c.i
.PHONY : external/glad/src/glad.i

# target to preprocess a source file
external/glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/external/glad/src/glad.c.i
.PHONY : external/glad/src/glad.c.i

external/glad/src/glad.s: external/glad/src/glad.c.s
.PHONY : external/glad/src/glad.s

# target to generate assembly for a file
external/glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/external/glad/src/glad.c.s
.PHONY : external/glad/src/glad.c.s

external/imgui/backends/imgui_impl_glfw.o: external/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : external/imgui/backends/imgui_impl_glfw.o

# target to build an object file
external/imgui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/external/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : external/imgui/backends/imgui_impl_glfw.cpp.o

external/imgui/backends/imgui_impl_glfw.i: external/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : external/imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
external/imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/external/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : external/imgui/backends/imgui_impl_glfw.cpp.i

external/imgui/backends/imgui_impl_glfw.s: external/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : external/imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
external/imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/external/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : external/imgui/backends/imgui_impl_glfw.cpp.s

external/imgui/backends/imgui_impl_opengl3.o: external/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : external/imgui/backends/imgui_impl_opengl3.o

# target to build an object file
external/imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/external/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : external/imgui/backends/imgui_impl_opengl3.cpp.o

external/imgui/backends/imgui_impl_opengl3.i: external/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : external/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
external/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/external/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : external/imgui/backends/imgui_impl_opengl3.cpp.i

external/imgui/backends/imgui_impl_opengl3.s: external/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : external/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
external/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/external/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : external/imgui/backends/imgui_impl_opengl3.cpp.s

external/imgui/imgui.o: external/imgui/imgui.cpp.o
.PHONY : external/imgui/imgui.o

# target to build an object file
external/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/external/imgui/imgui.cpp.o
.PHONY : external/imgui/imgui.cpp.o

external/imgui/imgui.i: external/imgui/imgui.cpp.i
.PHONY : external/imgui/imgui.i

# target to preprocess a source file
external/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/external/imgui/imgui.cpp.i
.PHONY : external/imgui/imgui.cpp.i

external/imgui/imgui.s: external/imgui/imgui.cpp.s
.PHONY : external/imgui/imgui.s

# target to generate assembly for a file
external/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/external/imgui/imgui.cpp.s
.PHONY : external/imgui/imgui.cpp.s

external/imgui/imgui_demo.o: external/imgui/imgui_demo.cpp.o
.PHONY : external/imgui/imgui_demo.o

# target to build an object file
external/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/external/imgui/imgui_demo.cpp.o
.PHONY : external/imgui/imgui_demo.cpp.o

external/imgui/imgui_demo.i: external/imgui/imgui_demo.cpp.i
.PHONY : external/imgui/imgui_demo.i

# target to preprocess a source file
external/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/external/imgui/imgui_demo.cpp.i
.PHONY : external/imgui/imgui_demo.cpp.i

external/imgui/imgui_demo.s: external/imgui/imgui_demo.cpp.s
.PHONY : external/imgui/imgui_demo.s

# target to generate assembly for a file
external/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/external/imgui/imgui_demo.cpp.s
.PHONY : external/imgui/imgui_demo.cpp.s

external/imgui/imgui_draw.o: external/imgui/imgui_draw.cpp.o
.PHONY : external/imgui/imgui_draw.o

# target to build an object file
external/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/external/imgui/imgui_draw.cpp.o
.PHONY : external/imgui/imgui_draw.cpp.o

external/imgui/imgui_draw.i: external/imgui/imgui_draw.cpp.i
.PHONY : external/imgui/imgui_draw.i

# target to preprocess a source file
external/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/external/imgui/imgui_draw.cpp.i
.PHONY : external/imgui/imgui_draw.cpp.i

external/imgui/imgui_draw.s: external/imgui/imgui_draw.cpp.s
.PHONY : external/imgui/imgui_draw.s

# target to generate assembly for a file
external/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/external/imgui/imgui_draw.cpp.s
.PHONY : external/imgui/imgui_draw.cpp.s

external/imgui/imgui_tables.o: external/imgui/imgui_tables.cpp.o
.PHONY : external/imgui/imgui_tables.o

# target to build an object file
external/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/external/imgui/imgui_tables.cpp.o
.PHONY : external/imgui/imgui_tables.cpp.o

external/imgui/imgui_tables.i: external/imgui/imgui_tables.cpp.i
.PHONY : external/imgui/imgui_tables.i

# target to preprocess a source file
external/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/external/imgui/imgui_tables.cpp.i
.PHONY : external/imgui/imgui_tables.cpp.i

external/imgui/imgui_tables.s: external/imgui/imgui_tables.cpp.s
.PHONY : external/imgui/imgui_tables.s

# target to generate assembly for a file
external/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/external/imgui/imgui_tables.cpp.s
.PHONY : external/imgui/imgui_tables.cpp.s

external/imgui/imgui_widgets.o: external/imgui/imgui_widgets.cpp.o
.PHONY : external/imgui/imgui_widgets.o

# target to build an object file
external/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/external/imgui/imgui_widgets.cpp.o
.PHONY : external/imgui/imgui_widgets.cpp.o

external/imgui/imgui_widgets.i: external/imgui/imgui_widgets.cpp.i
.PHONY : external/imgui/imgui_widgets.i

# target to preprocess a source file
external/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/external/imgui/imgui_widgets.cpp.i
.PHONY : external/imgui/imgui_widgets.cpp.i

external/imgui/imgui_widgets.s: external/imgui/imgui_widgets.cpp.s
.PHONY : external/imgui/imgui_widgets.s

# target to generate assembly for a file
external/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/external/imgui/imgui_widgets.cpp.s
.PHONY : external/imgui/imgui_widgets.cpp.s

external/stb/stb_image.o: external/stb/stb_image.cpp.o
.PHONY : external/stb/stb_image.o

# target to build an object file
external/stb/stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/external/stb/stb_image.cpp.o
.PHONY : external/stb/stb_image.cpp.o

external/stb/stb_image.i: external/stb/stb_image.cpp.i
.PHONY : external/stb/stb_image.i

# target to preprocess a source file
external/stb/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/external/stb/stb_image.cpp.i
.PHONY : external/stb/stb_image.cpp.i

external/stb/stb_image.s: external/stb/stb_image.cpp.s
.PHONY : external/stb/stb_image.s

# target to generate assembly for a file
external/stb/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/external/stb/stb_image.cpp.s
.PHONY : external/stb/stb_image.cpp.s

src/asset/AssetSystem.o: src/asset/AssetSystem.cpp.o
.PHONY : src/asset/AssetSystem.o

# target to build an object file
src/asset/AssetSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/asset/AssetSystem.cpp.o
.PHONY : src/asset/AssetSystem.cpp.o

src/asset/AssetSystem.i: src/asset/AssetSystem.cpp.i
.PHONY : src/asset/AssetSystem.i

# target to preprocess a source file
src/asset/AssetSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/asset/AssetSystem.cpp.i
.PHONY : src/asset/AssetSystem.cpp.i

src/asset/AssetSystem.s: src/asset/AssetSystem.cpp.s
.PHONY : src/asset/AssetSystem.s

# target to generate assembly for a file
src/asset/AssetSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/asset/AssetSystem.cpp.s
.PHONY : src/asset/AssetSystem.cpp.s

src/asset/converters/OBJ_AssetConverter.o: src/asset/converters/OBJ_AssetConverter.cpp.o
.PHONY : src/asset/converters/OBJ_AssetConverter.o

# target to build an object file
src/asset/converters/OBJ_AssetConverter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/asset/converters/OBJ_AssetConverter.cpp.o
.PHONY : src/asset/converters/OBJ_AssetConverter.cpp.o

src/asset/converters/OBJ_AssetConverter.i: src/asset/converters/OBJ_AssetConverter.cpp.i
.PHONY : src/asset/converters/OBJ_AssetConverter.i

# target to preprocess a source file
src/asset/converters/OBJ_AssetConverter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/asset/converters/OBJ_AssetConverter.cpp.i
.PHONY : src/asset/converters/OBJ_AssetConverter.cpp.i

src/asset/converters/OBJ_AssetConverter.s: src/asset/converters/OBJ_AssetConverter.cpp.s
.PHONY : src/asset/converters/OBJ_AssetConverter.s

# target to generate assembly for a file
src/asset/converters/OBJ_AssetConverter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/asset/converters/OBJ_AssetConverter.cpp.s
.PHONY : src/asset/converters/OBJ_AssetConverter.cpp.s

src/core/GUIContext.o: src/core/GUIContext.cpp.o
.PHONY : src/core/GUIContext.o

# target to build an object file
src/core/GUIContext.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/core/GUIContext.cpp.o
.PHONY : src/core/GUIContext.cpp.o

src/core/GUIContext.i: src/core/GUIContext.cpp.i
.PHONY : src/core/GUIContext.i

# target to preprocess a source file
src/core/GUIContext.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/core/GUIContext.cpp.i
.PHONY : src/core/GUIContext.cpp.i

src/core/GUIContext.s: src/core/GUIContext.cpp.s
.PHONY : src/core/GUIContext.s

# target to generate assembly for a file
src/core/GUIContext.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/core/GUIContext.cpp.s
.PHONY : src/core/GUIContext.cpp.s

src/core/PearlEngine.o: src/core/PearlEngine.cpp.o
.PHONY : src/core/PearlEngine.o

# target to build an object file
src/core/PearlEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/core/PearlEngine.cpp.o
.PHONY : src/core/PearlEngine.cpp.o

src/core/PearlEngine.i: src/core/PearlEngine.cpp.i
.PHONY : src/core/PearlEngine.i

# target to preprocess a source file
src/core/PearlEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/core/PearlEngine.cpp.i
.PHONY : src/core/PearlEngine.cpp.i

src/core/PearlEngine.s: src/core/PearlEngine.cpp.s
.PHONY : src/core/PearlEngine.s

# target to generate assembly for a file
src/core/PearlEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/core/PearlEngine.cpp.s
.PHONY : src/core/PearlEngine.cpp.s

src/core/PearlWindow.o: src/core/PearlWindow.cpp.o
.PHONY : src/core/PearlWindow.o

# target to build an object file
src/core/PearlWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/core/PearlWindow.cpp.o
.PHONY : src/core/PearlWindow.cpp.o

src/core/PearlWindow.i: src/core/PearlWindow.cpp.i
.PHONY : src/core/PearlWindow.i

# target to preprocess a source file
src/core/PearlWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/core/PearlWindow.cpp.i
.PHONY : src/core/PearlWindow.cpp.i

src/core/PearlWindow.s: src/core/PearlWindow.cpp.s
.PHONY : src/core/PearlWindow.s

# target to generate assembly for a file
src/core/PearlWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/core/PearlWindow.cpp.s
.PHONY : src/core/PearlWindow.cpp.s

src/core/Scene.o: src/core/Scene.cpp.o
.PHONY : src/core/Scene.o

# target to build an object file
src/core/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/core/Scene.cpp.o
.PHONY : src/core/Scene.cpp.o

src/core/Scene.i: src/core/Scene.cpp.i
.PHONY : src/core/Scene.i

# target to preprocess a source file
src/core/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/core/Scene.cpp.i
.PHONY : src/core/Scene.cpp.i

src/core/Scene.s: src/core/Scene.cpp.s
.PHONY : src/core/Scene.s

# target to generate assembly for a file
src/core/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/core/Scene.cpp.s
.PHONY : src/core/Scene.cpp.s

src/core/Time.o: src/core/Time.cpp.o
.PHONY : src/core/Time.o

# target to build an object file
src/core/Time.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/core/Time.cpp.o
.PHONY : src/core/Time.cpp.o

src/core/Time.i: src/core/Time.cpp.i
.PHONY : src/core/Time.i

# target to preprocess a source file
src/core/Time.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/core/Time.cpp.i
.PHONY : src/core/Time.cpp.i

src/core/Time.s: src/core/Time.cpp.s
.PHONY : src/core/Time.s

# target to generate assembly for a file
src/core/Time.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/core/Time.cpp.s
.PHONY : src/core/Time.cpp.s

src/ecs/components/TransformComponent.o: src/ecs/components/TransformComponent.cpp.o
.PHONY : src/ecs/components/TransformComponent.o

# target to build an object file
src/ecs/components/TransformComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/ecs/components/TransformComponent.cpp.o
.PHONY : src/ecs/components/TransformComponent.cpp.o

src/ecs/components/TransformComponent.i: src/ecs/components/TransformComponent.cpp.i
.PHONY : src/ecs/components/TransformComponent.i

# target to preprocess a source file
src/ecs/components/TransformComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/ecs/components/TransformComponent.cpp.i
.PHONY : src/ecs/components/TransformComponent.cpp.i

src/ecs/components/TransformComponent.s: src/ecs/components/TransformComponent.cpp.s
.PHONY : src/ecs/components/TransformComponent.s

# target to generate assembly for a file
src/ecs/components/TransformComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/ecs/components/TransformComponent.cpp.s
.PHONY : src/ecs/components/TransformComponent.cpp.s

src/editor/MenuBar.o: src/editor/MenuBar.cpp.o
.PHONY : src/editor/MenuBar.o

# target to build an object file
src/editor/MenuBar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/MenuBar.cpp.o
.PHONY : src/editor/MenuBar.cpp.o

src/editor/MenuBar.i: src/editor/MenuBar.cpp.i
.PHONY : src/editor/MenuBar.i

# target to preprocess a source file
src/editor/MenuBar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/MenuBar.cpp.i
.PHONY : src/editor/MenuBar.cpp.i

src/editor/MenuBar.s: src/editor/MenuBar.cpp.s
.PHONY : src/editor/MenuBar.s

# target to generate assembly for a file
src/editor/MenuBar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/MenuBar.cpp.s
.PHONY : src/editor/MenuBar.cpp.s

src/editor/componenteditors/CameraComponentEditor.o: src/editor/componenteditors/CameraComponentEditor.cpp.o
.PHONY : src/editor/componenteditors/CameraComponentEditor.o

# target to build an object file
src/editor/componenteditors/CameraComponentEditor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/componenteditors/CameraComponentEditor.cpp.o
.PHONY : src/editor/componenteditors/CameraComponentEditor.cpp.o

src/editor/componenteditors/CameraComponentEditor.i: src/editor/componenteditors/CameraComponentEditor.cpp.i
.PHONY : src/editor/componenteditors/CameraComponentEditor.i

# target to preprocess a source file
src/editor/componenteditors/CameraComponentEditor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/componenteditors/CameraComponentEditor.cpp.i
.PHONY : src/editor/componenteditors/CameraComponentEditor.cpp.i

src/editor/componenteditors/CameraComponentEditor.s: src/editor/componenteditors/CameraComponentEditor.cpp.s
.PHONY : src/editor/componenteditors/CameraComponentEditor.s

# target to generate assembly for a file
src/editor/componenteditors/CameraComponentEditor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/componenteditors/CameraComponentEditor.cpp.s
.PHONY : src/editor/componenteditors/CameraComponentEditor.cpp.s

src/editor/componenteditors/RenderComponentEditor.o: src/editor/componenteditors/RenderComponentEditor.cpp.o
.PHONY : src/editor/componenteditors/RenderComponentEditor.o

# target to build an object file
src/editor/componenteditors/RenderComponentEditor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/componenteditors/RenderComponentEditor.cpp.o
.PHONY : src/editor/componenteditors/RenderComponentEditor.cpp.o

src/editor/componenteditors/RenderComponentEditor.i: src/editor/componenteditors/RenderComponentEditor.cpp.i
.PHONY : src/editor/componenteditors/RenderComponentEditor.i

# target to preprocess a source file
src/editor/componenteditors/RenderComponentEditor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/componenteditors/RenderComponentEditor.cpp.i
.PHONY : src/editor/componenteditors/RenderComponentEditor.cpp.i

src/editor/componenteditors/RenderComponentEditor.s: src/editor/componenteditors/RenderComponentEditor.cpp.s
.PHONY : src/editor/componenteditors/RenderComponentEditor.s

# target to generate assembly for a file
src/editor/componenteditors/RenderComponentEditor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/componenteditors/RenderComponentEditor.cpp.s
.PHONY : src/editor/componenteditors/RenderComponentEditor.cpp.s

src/editor/componenteditors/TransformComponentEditor.o: src/editor/componenteditors/TransformComponentEditor.cpp.o
.PHONY : src/editor/componenteditors/TransformComponentEditor.o

# target to build an object file
src/editor/componenteditors/TransformComponentEditor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/componenteditors/TransformComponentEditor.cpp.o
.PHONY : src/editor/componenteditors/TransformComponentEditor.cpp.o

src/editor/componenteditors/TransformComponentEditor.i: src/editor/componenteditors/TransformComponentEditor.cpp.i
.PHONY : src/editor/componenteditors/TransformComponentEditor.i

# target to preprocess a source file
src/editor/componenteditors/TransformComponentEditor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/componenteditors/TransformComponentEditor.cpp.i
.PHONY : src/editor/componenteditors/TransformComponentEditor.cpp.i

src/editor/componenteditors/TransformComponentEditor.s: src/editor/componenteditors/TransformComponentEditor.cpp.s
.PHONY : src/editor/componenteditors/TransformComponentEditor.s

# target to generate assembly for a file
src/editor/componenteditors/TransformComponentEditor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/componenteditors/TransformComponentEditor.cpp.s
.PHONY : src/editor/componenteditors/TransformComponentEditor.cpp.s

src/editor/panels/AssetEditorPanel.o: src/editor/panels/AssetEditorPanel.cpp.o
.PHONY : src/editor/panels/AssetEditorPanel.o

# target to build an object file
src/editor/panels/AssetEditorPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/panels/AssetEditorPanel.cpp.o
.PHONY : src/editor/panels/AssetEditorPanel.cpp.o

src/editor/panels/AssetEditorPanel.i: src/editor/panels/AssetEditorPanel.cpp.i
.PHONY : src/editor/panels/AssetEditorPanel.i

# target to preprocess a source file
src/editor/panels/AssetEditorPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/panels/AssetEditorPanel.cpp.i
.PHONY : src/editor/panels/AssetEditorPanel.cpp.i

src/editor/panels/AssetEditorPanel.s: src/editor/panels/AssetEditorPanel.cpp.s
.PHONY : src/editor/panels/AssetEditorPanel.s

# target to generate assembly for a file
src/editor/panels/AssetEditorPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/panels/AssetEditorPanel.cpp.s
.PHONY : src/editor/panels/AssetEditorPanel.cpp.s

src/editor/panels/InspectorEditorPanel.o: src/editor/panels/InspectorEditorPanel.cpp.o
.PHONY : src/editor/panels/InspectorEditorPanel.o

# target to build an object file
src/editor/panels/InspectorEditorPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/panels/InspectorEditorPanel.cpp.o
.PHONY : src/editor/panels/InspectorEditorPanel.cpp.o

src/editor/panels/InspectorEditorPanel.i: src/editor/panels/InspectorEditorPanel.cpp.i
.PHONY : src/editor/panels/InspectorEditorPanel.i

# target to preprocess a source file
src/editor/panels/InspectorEditorPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/panels/InspectorEditorPanel.cpp.i
.PHONY : src/editor/panels/InspectorEditorPanel.cpp.i

src/editor/panels/InspectorEditorPanel.s: src/editor/panels/InspectorEditorPanel.cpp.s
.PHONY : src/editor/panels/InspectorEditorPanel.s

# target to generate assembly for a file
src/editor/panels/InspectorEditorPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/panels/InspectorEditorPanel.cpp.s
.PHONY : src/editor/panels/InspectorEditorPanel.cpp.s

src/editor/panels/LoggerEditorPanel.o: src/editor/panels/LoggerEditorPanel.cpp.o
.PHONY : src/editor/panels/LoggerEditorPanel.o

# target to build an object file
src/editor/panels/LoggerEditorPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/panels/LoggerEditorPanel.cpp.o
.PHONY : src/editor/panels/LoggerEditorPanel.cpp.o

src/editor/panels/LoggerEditorPanel.i: src/editor/panels/LoggerEditorPanel.cpp.i
.PHONY : src/editor/panels/LoggerEditorPanel.i

# target to preprocess a source file
src/editor/panels/LoggerEditorPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/panels/LoggerEditorPanel.cpp.i
.PHONY : src/editor/panels/LoggerEditorPanel.cpp.i

src/editor/panels/LoggerEditorPanel.s: src/editor/panels/LoggerEditorPanel.cpp.s
.PHONY : src/editor/panels/LoggerEditorPanel.s

# target to generate assembly for a file
src/editor/panels/LoggerEditorPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/panels/LoggerEditorPanel.cpp.s
.PHONY : src/editor/panels/LoggerEditorPanel.cpp.s

src/editor/panels/ProjectEditorPanel.o: src/editor/panels/ProjectEditorPanel.cpp.o
.PHONY : src/editor/panels/ProjectEditorPanel.o

# target to build an object file
src/editor/panels/ProjectEditorPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/panels/ProjectEditorPanel.cpp.o
.PHONY : src/editor/panels/ProjectEditorPanel.cpp.o

src/editor/panels/ProjectEditorPanel.i: src/editor/panels/ProjectEditorPanel.cpp.i
.PHONY : src/editor/panels/ProjectEditorPanel.i

# target to preprocess a source file
src/editor/panels/ProjectEditorPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/panels/ProjectEditorPanel.cpp.i
.PHONY : src/editor/panels/ProjectEditorPanel.cpp.i

src/editor/panels/ProjectEditorPanel.s: src/editor/panels/ProjectEditorPanel.cpp.s
.PHONY : src/editor/panels/ProjectEditorPanel.s

# target to generate assembly for a file
src/editor/panels/ProjectEditorPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/panels/ProjectEditorPanel.cpp.s
.PHONY : src/editor/panels/ProjectEditorPanel.cpp.s

src/editor/panels/ResourceEditorPanel.o: src/editor/panels/ResourceEditorPanel.cpp.o
.PHONY : src/editor/panels/ResourceEditorPanel.o

# target to build an object file
src/editor/panels/ResourceEditorPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/panels/ResourceEditorPanel.cpp.o
.PHONY : src/editor/panels/ResourceEditorPanel.cpp.o

src/editor/panels/ResourceEditorPanel.i: src/editor/panels/ResourceEditorPanel.cpp.i
.PHONY : src/editor/panels/ResourceEditorPanel.i

# target to preprocess a source file
src/editor/panels/ResourceEditorPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/panels/ResourceEditorPanel.cpp.i
.PHONY : src/editor/panels/ResourceEditorPanel.cpp.i

src/editor/panels/ResourceEditorPanel.s: src/editor/panels/ResourceEditorPanel.cpp.s
.PHONY : src/editor/panels/ResourceEditorPanel.s

# target to generate assembly for a file
src/editor/panels/ResourceEditorPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/panels/ResourceEditorPanel.cpp.s
.PHONY : src/editor/panels/ResourceEditorPanel.cpp.s

src/editor/panels/SceneHierarchyEditorPanel.o: src/editor/panels/SceneHierarchyEditorPanel.cpp.o
.PHONY : src/editor/panels/SceneHierarchyEditorPanel.o

# target to build an object file
src/editor/panels/SceneHierarchyEditorPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/panels/SceneHierarchyEditorPanel.cpp.o
.PHONY : src/editor/panels/SceneHierarchyEditorPanel.cpp.o

src/editor/panels/SceneHierarchyEditorPanel.i: src/editor/panels/SceneHierarchyEditorPanel.cpp.i
.PHONY : src/editor/panels/SceneHierarchyEditorPanel.i

# target to preprocess a source file
src/editor/panels/SceneHierarchyEditorPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/panels/SceneHierarchyEditorPanel.cpp.i
.PHONY : src/editor/panels/SceneHierarchyEditorPanel.cpp.i

src/editor/panels/SceneHierarchyEditorPanel.s: src/editor/panels/SceneHierarchyEditorPanel.cpp.s
.PHONY : src/editor/panels/SceneHierarchyEditorPanel.s

# target to generate assembly for a file
src/editor/panels/SceneHierarchyEditorPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/panels/SceneHierarchyEditorPanel.cpp.s
.PHONY : src/editor/panels/SceneHierarchyEditorPanel.cpp.s

src/editor/panels/ViewportEditorPanel.o: src/editor/panels/ViewportEditorPanel.cpp.o
.PHONY : src/editor/panels/ViewportEditorPanel.o

# target to build an object file
src/editor/panels/ViewportEditorPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/panels/ViewportEditorPanel.cpp.o
.PHONY : src/editor/panels/ViewportEditorPanel.cpp.o

src/editor/panels/ViewportEditorPanel.i: src/editor/panels/ViewportEditorPanel.cpp.i
.PHONY : src/editor/panels/ViewportEditorPanel.i

# target to preprocess a source file
src/editor/panels/ViewportEditorPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/panels/ViewportEditorPanel.cpp.i
.PHONY : src/editor/panels/ViewportEditorPanel.cpp.i

src/editor/panels/ViewportEditorPanel.s: src/editor/panels/ViewportEditorPanel.cpp.s
.PHONY : src/editor/panels/ViewportEditorPanel.s

# target to generate assembly for a file
src/editor/panels/ViewportEditorPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/editor/panels/ViewportEditorPanel.cpp.s
.PHONY : src/editor/panels/ViewportEditorPanel.cpp.s

src/geometry/Cube.o: src/geometry/Cube.cpp.o
.PHONY : src/geometry/Cube.o

# target to build an object file
src/geometry/Cube.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/geometry/Cube.cpp.o
.PHONY : src/geometry/Cube.cpp.o

src/geometry/Cube.i: src/geometry/Cube.cpp.i
.PHONY : src/geometry/Cube.i

# target to preprocess a source file
src/geometry/Cube.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/geometry/Cube.cpp.i
.PHONY : src/geometry/Cube.cpp.i

src/geometry/Cube.s: src/geometry/Cube.cpp.s
.PHONY : src/geometry/Cube.s

# target to generate assembly for a file
src/geometry/Cube.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/geometry/Cube.cpp.s
.PHONY : src/geometry/Cube.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/project/Project.o: src/project/Project.cpp.o
.PHONY : src/project/Project.o

# target to build an object file
src/project/Project.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/project/Project.cpp.o
.PHONY : src/project/Project.cpp.o

src/project/Project.i: src/project/Project.cpp.i
.PHONY : src/project/Project.i

# target to preprocess a source file
src/project/Project.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/project/Project.cpp.i
.PHONY : src/project/Project.cpp.i

src/project/Project.s: src/project/Project.cpp.s
.PHONY : src/project/Project.s

# target to generate assembly for a file
src/project/Project.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/project/Project.cpp.s
.PHONY : src/project/Project.cpp.s

src/rendering/Camera.o: src/rendering/Camera.cpp.o
.PHONY : src/rendering/Camera.o

# target to build an object file
src/rendering/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/rendering/Camera.cpp.o
.PHONY : src/rendering/Camera.cpp.o

src/rendering/Camera.i: src/rendering/Camera.cpp.i
.PHONY : src/rendering/Camera.i

# target to preprocess a source file
src/rendering/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/rendering/Camera.cpp.i
.PHONY : src/rendering/Camera.cpp.i

src/rendering/Camera.s: src/rendering/Camera.cpp.s
.PHONY : src/rendering/Camera.s

# target to generate assembly for a file
src/rendering/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/rendering/Camera.cpp.s
.PHONY : src/rendering/Camera.cpp.s

src/rendering/FrameBuffer.o: src/rendering/FrameBuffer.cpp.o
.PHONY : src/rendering/FrameBuffer.o

# target to build an object file
src/rendering/FrameBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/rendering/FrameBuffer.cpp.o
.PHONY : src/rendering/FrameBuffer.cpp.o

src/rendering/FrameBuffer.i: src/rendering/FrameBuffer.cpp.i
.PHONY : src/rendering/FrameBuffer.i

# target to preprocess a source file
src/rendering/FrameBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/rendering/FrameBuffer.cpp.i
.PHONY : src/rendering/FrameBuffer.cpp.i

src/rendering/FrameBuffer.s: src/rendering/FrameBuffer.cpp.s
.PHONY : src/rendering/FrameBuffer.s

# target to generate assembly for a file
src/rendering/FrameBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/rendering/FrameBuffer.cpp.s
.PHONY : src/rendering/FrameBuffer.cpp.s

src/rendering/Renderer.o: src/rendering/Renderer.cpp.o
.PHONY : src/rendering/Renderer.o

# target to build an object file
src/rendering/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/rendering/Renderer.cpp.o
.PHONY : src/rendering/Renderer.cpp.o

src/rendering/Renderer.i: src/rendering/Renderer.cpp.i
.PHONY : src/rendering/Renderer.i

# target to preprocess a source file
src/rendering/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/rendering/Renderer.cpp.i
.PHONY : src/rendering/Renderer.cpp.i

src/rendering/Renderer.s: src/rendering/Renderer.cpp.s
.PHONY : src/rendering/Renderer.s

# target to generate assembly for a file
src/rendering/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/rendering/Renderer.cpp.s
.PHONY : src/rendering/Renderer.cpp.s

src/resource/converters/Mesh_ResourceConverter.o: src/resource/converters/Mesh_ResourceConverter.cpp.o
.PHONY : src/resource/converters/Mesh_ResourceConverter.o

# target to build an object file
src/resource/converters/Mesh_ResourceConverter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/converters/Mesh_ResourceConverter.cpp.o
.PHONY : src/resource/converters/Mesh_ResourceConverter.cpp.o

src/resource/converters/Mesh_ResourceConverter.i: src/resource/converters/Mesh_ResourceConverter.cpp.i
.PHONY : src/resource/converters/Mesh_ResourceConverter.i

# target to preprocess a source file
src/resource/converters/Mesh_ResourceConverter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/converters/Mesh_ResourceConverter.cpp.i
.PHONY : src/resource/converters/Mesh_ResourceConverter.cpp.i

src/resource/converters/Mesh_ResourceConverter.s: src/resource/converters/Mesh_ResourceConverter.cpp.s
.PHONY : src/resource/converters/Mesh_ResourceConverter.s

# target to generate assembly for a file
src/resource/converters/Mesh_ResourceConverter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/converters/Mesh_ResourceConverter.cpp.s
.PHONY : src/resource/converters/Mesh_ResourceConverter.cpp.s

src/resource/loaders/materialLoaders.o: src/resource/loaders/materialLoaders.cpp.o
.PHONY : src/resource/loaders/materialLoaders.o

# target to build an object file
src/resource/loaders/materialLoaders.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/loaders/materialLoaders.cpp.o
.PHONY : src/resource/loaders/materialLoaders.cpp.o

src/resource/loaders/materialLoaders.i: src/resource/loaders/materialLoaders.cpp.i
.PHONY : src/resource/loaders/materialLoaders.i

# target to preprocess a source file
src/resource/loaders/materialLoaders.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/loaders/materialLoaders.cpp.i
.PHONY : src/resource/loaders/materialLoaders.cpp.i

src/resource/loaders/materialLoaders.s: src/resource/loaders/materialLoaders.cpp.s
.PHONY : src/resource/loaders/materialLoaders.s

# target to generate assembly for a file
src/resource/loaders/materialLoaders.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/loaders/materialLoaders.cpp.s
.PHONY : src/resource/loaders/materialLoaders.cpp.s

src/resource/loaders/shaderLoaders.o: src/resource/loaders/shaderLoaders.cpp.o
.PHONY : src/resource/loaders/shaderLoaders.o

# target to build an object file
src/resource/loaders/shaderLoaders.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/loaders/shaderLoaders.cpp.o
.PHONY : src/resource/loaders/shaderLoaders.cpp.o

src/resource/loaders/shaderLoaders.i: src/resource/loaders/shaderLoaders.cpp.i
.PHONY : src/resource/loaders/shaderLoaders.i

# target to preprocess a source file
src/resource/loaders/shaderLoaders.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/loaders/shaderLoaders.cpp.i
.PHONY : src/resource/loaders/shaderLoaders.cpp.i

src/resource/loaders/shaderLoaders.s: src/resource/loaders/shaderLoaders.cpp.s
.PHONY : src/resource/loaders/shaderLoaders.s

# target to generate assembly for a file
src/resource/loaders/shaderLoaders.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/loaders/shaderLoaders.cpp.s
.PHONY : src/resource/loaders/shaderLoaders.cpp.s

src/resource/loaders/textureLoaders.o: src/resource/loaders/textureLoaders.cpp.o
.PHONY : src/resource/loaders/textureLoaders.o

# target to build an object file
src/resource/loaders/textureLoaders.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/loaders/textureLoaders.cpp.o
.PHONY : src/resource/loaders/textureLoaders.cpp.o

src/resource/loaders/textureLoaders.i: src/resource/loaders/textureLoaders.cpp.i
.PHONY : src/resource/loaders/textureLoaders.i

# target to preprocess a source file
src/resource/loaders/textureLoaders.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/loaders/textureLoaders.cpp.i
.PHONY : src/resource/loaders/textureLoaders.cpp.i

src/resource/loaders/textureLoaders.s: src/resource/loaders/textureLoaders.cpp.s
.PHONY : src/resource/loaders/textureLoaders.s

# target to generate assembly for a file
src/resource/loaders/textureLoaders.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/loaders/textureLoaders.cpp.s
.PHONY : src/resource/loaders/textureLoaders.cpp.s

src/resource/resources/MaterialData.o: src/resource/resources/MaterialData.cpp.o
.PHONY : src/resource/resources/MaterialData.o

# target to build an object file
src/resource/resources/MaterialData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/resources/MaterialData.cpp.o
.PHONY : src/resource/resources/MaterialData.cpp.o

src/resource/resources/MaterialData.i: src/resource/resources/MaterialData.cpp.i
.PHONY : src/resource/resources/MaterialData.i

# target to preprocess a source file
src/resource/resources/MaterialData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/resources/MaterialData.cpp.i
.PHONY : src/resource/resources/MaterialData.cpp.i

src/resource/resources/MaterialData.s: src/resource/resources/MaterialData.cpp.s
.PHONY : src/resource/resources/MaterialData.s

# target to generate assembly for a file
src/resource/resources/MaterialData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/resources/MaterialData.cpp.s
.PHONY : src/resource/resources/MaterialData.cpp.s

src/resource/resources/Mesh.o: src/resource/resources/Mesh.cpp.o
.PHONY : src/resource/resources/Mesh.o

# target to build an object file
src/resource/resources/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/resources/Mesh.cpp.o
.PHONY : src/resource/resources/Mesh.cpp.o

src/resource/resources/Mesh.i: src/resource/resources/Mesh.cpp.i
.PHONY : src/resource/resources/Mesh.i

# target to preprocess a source file
src/resource/resources/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/resources/Mesh.cpp.i
.PHONY : src/resource/resources/Mesh.cpp.i

src/resource/resources/Mesh.s: src/resource/resources/Mesh.cpp.s
.PHONY : src/resource/resources/Mesh.s

# target to generate assembly for a file
src/resource/resources/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/resources/Mesh.cpp.s
.PHONY : src/resource/resources/Mesh.cpp.s

src/resource/resources/ShaderData.o: src/resource/resources/ShaderData.cpp.o
.PHONY : src/resource/resources/ShaderData.o

# target to build an object file
src/resource/resources/ShaderData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/resources/ShaderData.cpp.o
.PHONY : src/resource/resources/ShaderData.cpp.o

src/resource/resources/ShaderData.i: src/resource/resources/ShaderData.cpp.i
.PHONY : src/resource/resources/ShaderData.i

# target to preprocess a source file
src/resource/resources/ShaderData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/resources/ShaderData.cpp.i
.PHONY : src/resource/resources/ShaderData.cpp.i

src/resource/resources/ShaderData.s: src/resource/resources/ShaderData.cpp.s
.PHONY : src/resource/resources/ShaderData.s

# target to generate assembly for a file
src/resource/resources/ShaderData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/resources/ShaderData.cpp.s
.PHONY : src/resource/resources/ShaderData.cpp.s

src/resource/resources/TextureData.o: src/resource/resources/TextureData.cpp.o
.PHONY : src/resource/resources/TextureData.o

# target to build an object file
src/resource/resources/TextureData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/resources/TextureData.cpp.o
.PHONY : src/resource/resources/TextureData.cpp.o

src/resource/resources/TextureData.i: src/resource/resources/TextureData.cpp.i
.PHONY : src/resource/resources/TextureData.i

# target to preprocess a source file
src/resource/resources/TextureData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/resources/TextureData.cpp.i
.PHONY : src/resource/resources/TextureData.cpp.i

src/resource/resources/TextureData.s: src/resource/resources/TextureData.cpp.s
.PHONY : src/resource/resources/TextureData.s

# target to generate assembly for a file
src/resource/resources/TextureData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/resource/resources/TextureData.cpp.s
.PHONY : src/resource/resources/TextureData.cpp.s

src/utils/CameraController.o: src/utils/CameraController.cpp.o
.PHONY : src/utils/CameraController.o

# target to build an object file
src/utils/CameraController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/utils/CameraController.cpp.o
.PHONY : src/utils/CameraController.cpp.o

src/utils/CameraController.i: src/utils/CameraController.cpp.i
.PHONY : src/utils/CameraController.i

# target to preprocess a source file
src/utils/CameraController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/utils/CameraController.cpp.i
.PHONY : src/utils/CameraController.cpp.i

src/utils/CameraController.s: src/utils/CameraController.cpp.s
.PHONY : src/utils/CameraController.s

# target to generate assembly for a file
src/utils/CameraController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_engine.dir/build.make CMakeFiles/game_engine.dir/src/utils/CameraController.cpp.s
.PHONY : src/utils/CameraController.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... travis_doc"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... game_engine"
	@echo "... glad"
	@echo "... glfw"
	@echo "... imgui"
	@echo "... external/glad/src/glad.o"
	@echo "... external/glad/src/glad.i"
	@echo "... external/glad/src/glad.s"
	@echo "... external/imgui/backends/imgui_impl_glfw.o"
	@echo "... external/imgui/backends/imgui_impl_glfw.i"
	@echo "... external/imgui/backends/imgui_impl_glfw.s"
	@echo "... external/imgui/backends/imgui_impl_opengl3.o"
	@echo "... external/imgui/backends/imgui_impl_opengl3.i"
	@echo "... external/imgui/backends/imgui_impl_opengl3.s"
	@echo "... external/imgui/imgui.o"
	@echo "... external/imgui/imgui.i"
	@echo "... external/imgui/imgui.s"
	@echo "... external/imgui/imgui_demo.o"
	@echo "... external/imgui/imgui_demo.i"
	@echo "... external/imgui/imgui_demo.s"
	@echo "... external/imgui/imgui_draw.o"
	@echo "... external/imgui/imgui_draw.i"
	@echo "... external/imgui/imgui_draw.s"
	@echo "... external/imgui/imgui_tables.o"
	@echo "... external/imgui/imgui_tables.i"
	@echo "... external/imgui/imgui_tables.s"
	@echo "... external/imgui/imgui_widgets.o"
	@echo "... external/imgui/imgui_widgets.i"
	@echo "... external/imgui/imgui_widgets.s"
	@echo "... external/stb/stb_image.o"
	@echo "... external/stb/stb_image.i"
	@echo "... external/stb/stb_image.s"
	@echo "... src/asset/AssetSystem.o"
	@echo "... src/asset/AssetSystem.i"
	@echo "... src/asset/AssetSystem.s"
	@echo "... src/asset/converters/OBJ_AssetConverter.o"
	@echo "... src/asset/converters/OBJ_AssetConverter.i"
	@echo "... src/asset/converters/OBJ_AssetConverter.s"
	@echo "... src/core/GUIContext.o"
	@echo "... src/core/GUIContext.i"
	@echo "... src/core/GUIContext.s"
	@echo "... src/core/PearlEngine.o"
	@echo "... src/core/PearlEngine.i"
	@echo "... src/core/PearlEngine.s"
	@echo "... src/core/PearlWindow.o"
	@echo "... src/core/PearlWindow.i"
	@echo "... src/core/PearlWindow.s"
	@echo "... src/core/Scene.o"
	@echo "... src/core/Scene.i"
	@echo "... src/core/Scene.s"
	@echo "... src/core/Time.o"
	@echo "... src/core/Time.i"
	@echo "... src/core/Time.s"
	@echo "... src/ecs/components/TransformComponent.o"
	@echo "... src/ecs/components/TransformComponent.i"
	@echo "... src/ecs/components/TransformComponent.s"
	@echo "... src/editor/MenuBar.o"
	@echo "... src/editor/MenuBar.i"
	@echo "... src/editor/MenuBar.s"
	@echo "... src/editor/componenteditors/CameraComponentEditor.o"
	@echo "... src/editor/componenteditors/CameraComponentEditor.i"
	@echo "... src/editor/componenteditors/CameraComponentEditor.s"
	@echo "... src/editor/componenteditors/RenderComponentEditor.o"
	@echo "... src/editor/componenteditors/RenderComponentEditor.i"
	@echo "... src/editor/componenteditors/RenderComponentEditor.s"
	@echo "... src/editor/componenteditors/TransformComponentEditor.o"
	@echo "... src/editor/componenteditors/TransformComponentEditor.i"
	@echo "... src/editor/componenteditors/TransformComponentEditor.s"
	@echo "... src/editor/panels/AssetEditorPanel.o"
	@echo "... src/editor/panels/AssetEditorPanel.i"
	@echo "... src/editor/panels/AssetEditorPanel.s"
	@echo "... src/editor/panels/InspectorEditorPanel.o"
	@echo "... src/editor/panels/InspectorEditorPanel.i"
	@echo "... src/editor/panels/InspectorEditorPanel.s"
	@echo "... src/editor/panels/LoggerEditorPanel.o"
	@echo "... src/editor/panels/LoggerEditorPanel.i"
	@echo "... src/editor/panels/LoggerEditorPanel.s"
	@echo "... src/editor/panels/ProjectEditorPanel.o"
	@echo "... src/editor/panels/ProjectEditorPanel.i"
	@echo "... src/editor/panels/ProjectEditorPanel.s"
	@echo "... src/editor/panels/ResourceEditorPanel.o"
	@echo "... src/editor/panels/ResourceEditorPanel.i"
	@echo "... src/editor/panels/ResourceEditorPanel.s"
	@echo "... src/editor/panels/SceneHierarchyEditorPanel.o"
	@echo "... src/editor/panels/SceneHierarchyEditorPanel.i"
	@echo "... src/editor/panels/SceneHierarchyEditorPanel.s"
	@echo "... src/editor/panels/ViewportEditorPanel.o"
	@echo "... src/editor/panels/ViewportEditorPanel.i"
	@echo "... src/editor/panels/ViewportEditorPanel.s"
	@echo "... src/geometry/Cube.o"
	@echo "... src/geometry/Cube.i"
	@echo "... src/geometry/Cube.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/project/Project.o"
	@echo "... src/project/Project.i"
	@echo "... src/project/Project.s"
	@echo "... src/rendering/Camera.o"
	@echo "... src/rendering/Camera.i"
	@echo "... src/rendering/Camera.s"
	@echo "... src/rendering/FrameBuffer.o"
	@echo "... src/rendering/FrameBuffer.i"
	@echo "... src/rendering/FrameBuffer.s"
	@echo "... src/rendering/Renderer.o"
	@echo "... src/rendering/Renderer.i"
	@echo "... src/rendering/Renderer.s"
	@echo "... src/resource/converters/Mesh_ResourceConverter.o"
	@echo "... src/resource/converters/Mesh_ResourceConverter.i"
	@echo "... src/resource/converters/Mesh_ResourceConverter.s"
	@echo "... src/resource/loaders/materialLoaders.o"
	@echo "... src/resource/loaders/materialLoaders.i"
	@echo "... src/resource/loaders/materialLoaders.s"
	@echo "... src/resource/loaders/shaderLoaders.o"
	@echo "... src/resource/loaders/shaderLoaders.i"
	@echo "... src/resource/loaders/shaderLoaders.s"
	@echo "... src/resource/loaders/textureLoaders.o"
	@echo "... src/resource/loaders/textureLoaders.i"
	@echo "... src/resource/loaders/textureLoaders.s"
	@echo "... src/resource/resources/MaterialData.o"
	@echo "... src/resource/resources/MaterialData.i"
	@echo "... src/resource/resources/MaterialData.s"
	@echo "... src/resource/resources/Mesh.o"
	@echo "... src/resource/resources/Mesh.i"
	@echo "... src/resource/resources/Mesh.s"
	@echo "... src/resource/resources/ShaderData.o"
	@echo "... src/resource/resources/ShaderData.i"
	@echo "... src/resource/resources/ShaderData.s"
	@echo "... src/resource/resources/TextureData.o"
	@echo "... src/resource/resources/TextureData.i"
	@echo "... src/resource/resources/TextureData.s"
	@echo "... src/utils/CameraController.o"
	@echo "... src/utils/CameraController.i"
	@echo "... src/utils/CameraController.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/elias/Projects/PearlEngine/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

